replicaCount: 1

image:
  repository: ghcr.io/shersch/cloudflare-operator
  pullPolicy: IfNotPresent
  tag: "v1"

serviceAccount:
  create: true
  automount: true

resources: 
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"