# permissions for end users to edit dnsrecords.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cloudflare-operator
    app.kubernetes.io/managed-by: kustomize
  name: dnsrecord-editor-role
rules:
- apiGroups:
  - cloudflare.local.dev
  resources:
  - dnsrecords
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudflare.local.dev
  resources:
  - dnsrecords/status
  verbs:
  - get
