apiVersion: cloudflare.local.dev/v1alpha1
kind: DNSRecord
metadata:
  labels:
    app.kubernetes.io/name: cloudflare-operator
    app.kubernetes.io/managed-by: kustomize
  name: dnsrecord-sample
spec:
  # TODO(user): Add fields here
